CREATE TABLE `seriesReservations` (
	`ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`createdOn` int(10) unsigned,
	`createdBy` varchar(30),
	`createdVia` varchar(20),
	`roomID` smallint(6),
	`startTime` int(10) unsigned,
	`endTime` int(10) unsigned,
	`modifiedOn` int(11),
	`modifiedBy` varchar(30),
	`username` varchar(25),
	`initials` varchar(10),
	`groupname` varchar(30),
	`comments` varchar(500),
	`allDay` tinyint(1),
	`frequency` tinyint(1),
	`weekdays` varchar(100),
	`seriesEndDate` int(10) unsigned,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;